<ul>
  <li>Version 1.0 - April 2008<br/>
      Initial Release
  </li>
  <li>Version 1.0.1 - August 2008<br/>
      Add a summaary field to the smarty data available for each item
      Now Require CMS 1.3.1
      Now Require CGExtensions 1.9
  </li> 
  <li>Version 1.1 - August 2008<br/>
      Add support for shipping modules that require shipping info.
  </li> 
  <li>Version 1.1.1 - October 2008<br/>
      Minor help changes.
  </li> 
  <li>Version 1.3 - December 2008<br/>
    <ul>
      <li>Remove all references to tax and shipping modules.</li>
      <li>Vastly expand the cart module api.</li>
      <li>Simplify default templates.</li>
    </ul>
  </li> 
  <li>Version 1.3.1 - January 2009<br/>
    <ul>
      <li>Bug fixes.</li>
      <li>Now display the total number of items in the cart, not just the number of rows.</li>
    </ul>
  <li>Version 1.4.1 - May 2009<br/>
    <ul>
      <li>Add a template for controlling the summary view output</li>
      <li>Fix serialization stuff</li>
    </ul>
  <li>Version 1.4.2 - May 2009<br/>
    <ul>
      <li>Bump minimum cms version to 1.5.3</li>
      <li>Fix issue with setting quantity to 0</li>
    </ul>
  </li> 
  <li>Version 1.5 - February 2010<br/>
    <ul>
      <li>Adds SKU support.</li>
    </ul>
  </li> 
  <li>Version 1.6 - April 2010<br/>
    <ul>
      <li>Now works with CGEcommerce Base.</li>
      <li>Remove some preferences that are now hosted in CGEcommerceBase</li>
    </ul>
  </li> 
  <li>Version 1.6.1 - April 2010<br/>
    <ul>
      <li>Minor adjustment to cart name.</li>
      <li>Move changelog to external.</li>
    </ul>
  </li> 
  <li>Version 1.6.2 - April 2010<br/>
    <ul>
      <li>Minor bug fix.</li>
    </ul>
  </li> 
  <li>Version 1.7 - June 2010<br/>
    <ul>
      <li>Changed to work with subscription items, and policies.</li>
    </ul>
  </li>
  <li>Version 1.7.1 - August 2010<br/>
    <ul>
      <li>Adds a parameter to the EraseCart method (may have to change soon)</li>
      <li>Adds the ability to selectively remove cart items.</li>
      <li>Adds the ability to selectively disallow the ability to adjust item quantities.</li>
    </ul>
  </li>
</ul>
